dist: xenial
language: node_js
cache: yarn
os:
  - windows
  - linux
  - osx
node_js:
  - '8'
  - '10'
  - '11'
before_install:
  - |
    # Use newer yarn than that pre-installed in the Travis image.
    curl -sSfL https://yarnpkg.com/install.sh | bash
    export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
install:
  - |
    yarn --frozen-lockfile
    yarn forever start node_modules/verdaccio/build/lib/cli.js --config verdaccio.yml
script:
  - yarn validate:eslintrc
  - yarn lint
  - yarn prettier:check
  - yarn test
  - scripts/test-create-project-ci.js
