strategy:
  matrix:
    node_8_x:
      node_version: 8.x
    node_10_x:
      node_version: 10.x
    node_11_x:
      node_version: 11.x

pool:
  vmImage: 'vs2017-win2016'

steps:
  - task: NodeTool@0
    displayName: Install Node.js
    inputs:
      versionSpec: $(node_version)

  - bash: |
      # Use newer yarn than that pre-installed in the Travis image.
      curl -sSfL https://yarnpkg.com/install.sh | bash
      export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
    displayName: Yarn bootstrapping
  - bash: |
      yarn validate:eslintrc
      yarn lint
      yarn prettier:check
    displayName: Linting checks
  - bash: |
      yarn test
    displayName: AVA tests

  - bash: |
      scripts/test-create-project-ci.js
    displayName: create-project tests
